using Microsoft.Extensions.DependencyInjection;

namespace Autoredi.Attributes;

/// <summary>
/// Marks a class for compile-time registration in the Microsoft Dependency Injection container.
/// </summary>
/// <remarks>
/// <para>
/// Placing this attribute on a class makes the Autoredi source generator emit registration code
/// into the decorated assembly. The generator produces a static
/// <c>&lt;AssemblyName&gt;.Autoredi.AutorediServiceCollectionExtensions</c> class with extension
/// methods on <see cref="IServiceCollection"/>; consumer code must import that namespace with
/// <c>using &lt;AssemblyName&gt;.Autoredi;</c> to see the generated methods.
/// No reflection is used at any point, so the output is trimming- and AOT-safe.
/// </para>
/// <para>
/// All generated registrations use TryAdd semantics: they fill gaps and never override services
/// registered manually before the generated method is called, and calling the same generated
/// method twice adds no duplicate descriptors.
/// </para>
/// </remarks>
/// <example>
/// Register a concrete type as a singleton:
/// <code>
/// [Autoredi(ServiceLifetime.Singleton)]
/// public class AppConfig { }
///
/// var services = new ServiceCollection();
/// services.AddAutorediServices();          // generated by the source generator
/// var config = provider.GetRequiredService&lt;AppConfig&gt;();
/// </code>
/// </example>
/// <example>
/// Register against an interface, keyed for multiple implementations:
/// <code>
/// [Autoredi(ServiceLifetime.Scoped, typeof(IRepository), "sql")]
/// public class SqlRepository : IRepository { }
/// </code>
/// </example>
/// <param name="lifetime">
/// The service lifetime to register with. Defaults to <see cref="ServiceLifetime.Transient"/>.
/// Values outside the three enum members are rejected at compile time (AUTOREDI010).
/// </param>
/// <param name="interfaceType">
/// The optional service type (usually an interface) to register the class against. When set, no
/// self-registration is emitted. Must be an interface implemented by the decorated class, or the
/// generator reports AUTOREDI011 / AUTOREDI007 instead of emitting broken code.
/// </param>
/// <param name="serviceKey">
/// The optional key for keyed registrations (MEDI 8+), enabling multiple implementations of the
/// same service type. Resolve with <c>GetKeyedService</c> or inject via <c>[FromKeyedServices]</c>.
/// </param>
/// <param name="group">
/// The optional group name used to partition registrations into separate generated methods
/// (<c>AddAutorediServices{Group}</c>). Names that are not valid C# identifiers are sanitized
/// with warning AUTOREDI018.
/// </param>
/// <param name="priority">
/// Higher values are emitted earlier within their group (default 0). With TryAdd semantics,
/// emission order decides which registration fills a gap first when several target the same
/// service type. Ties break alphabetically by implementation type name.
/// </param>
[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
public sealed class AutorediAttribute(
    ServiceLifetime lifetime = ServiceLifetime.Transient,
    Type? interfaceType = null,
    string? serviceKey = null,
    string? group = null,
    int priority = 0
) : Attribute
{
    /// <summary>
    /// Gets the service lifetime for the registration.
    /// </summary>
    public ServiceLifetime Lifetime => lifetime;

    /// <summary>
    /// Gets the single interface to register the class against, if specified.
    /// </summary>
    /// <remarks>
    /// Ignored when <see cref="InterfaceTypes"/> has at least one entry.
    /// Positional attribute arguments cannot skip parameters: always pass the lifetime first,
    /// e.g. <c>[Autoredi(ServiceLifetime.Transient, typeof(IFoo))]</c>.
    /// </remarks>
    public Type? InterfaceType => interfaceType;

    /// <summary>
    /// Gets the service key for keyed registrations, if specified.
    /// </summary>
    public string? ServiceKey => serviceKey;

    /// <summary>
    /// Gets the group name controlling which generated method registers the class.
    /// </summary>
    public string? Group => group;

    /// <summary>
    /// Gets the registration priority (higher values are emitted first within the group).
    /// </summary>
    public int Priority => priority;

    /// <summary>
    /// Gets or sets the interfaces to register the class against. When provided with at least
    /// one entry it replaces <see cref="InterfaceType"/>, and no self-registration is emitted.
    /// </summary>
    /// <remarks>
    /// Each entry must be an interface implemented by the decorated class; otherwise the
    /// generator reports AUTOREDI011 / AUTOREDI007 at compile time.
    /// Because this is a property (constructor-parameter binding does not apply), set it with
    /// named-argument syntax; a collection expression keeps it concise.
    /// </remarks>
    /// <example>
    /// <code>
    /// [Autoredi(ServiceLifetime.Scoped, InterfaceTypes = [typeof(IRepo), typeof(ICache)])]
    /// public class RedisStore : IRepo, ICache { }
    /// </code>
    /// Generates one descriptor per interface sharing lifetime, key, group, and priority.
    /// </example>
    public Type[]? InterfaceTypes { get; set; }
}
