namespace Autoredi.Generators.Extraction;

internal static class AutorediAllServicesBuilder
{
    public static string Generate(string targetNamespace, string assemblyName, IReadOnlyList<string> assemblyNames)
    {
        var builder = new SourceBuilder();
        builder.AutoGenerated();
        builder.Using("Microsoft.Extensions.DependencyInjection");
        builder.Line();

        builder.Namespace(targetNamespace);

        builder.Class("public static partial", "AutorediServiceCollectionExtensions");
        builder.Block(b =>
        {
            GenerateAllServicesDocComment(b);
            b.Method("public static", "IServiceCollection", "AddAutorediServicesAll", "this IServiceCollection services");
            b.Block(methodBody =>
            {
                foreach (var name in assemblyNames)
                {
                    var suffix = AutorediNaming.ToIdentifierFragment(name);
                    methodBody.Line($"global::{name}.Autoredi.AutorediServiceCollectionExtensions.AddAutorediServices{suffix}(services);");
                }

                methodBody.Line("return services;");
            });
        });

        return builder.ToString();
    }

    private static void GenerateAllServicesDocComment(SourceBuilder builder)
    {
        builder.Line("/// <summary>");
        builder.Line("/// Registers all Autoredi services from this assembly and any referenced assemblies that define Autoredi registrations.");
        builder.Line("/// </summary>");
    }
}
