namespace Autoredi.Generators.Extraction;

/// <summary>
/// The generated extension-class source plus any output-stage diagnostics
/// (name sanitization warnings, method-name collisions).
/// </summary>
internal sealed record GeneratedResult(string Source, ImmutableArray<Diagnostic> Diagnostics);

/// <summary>
/// Generates the IServiceCollection extension methods for Autoredi registrations.
/// Registrations use TryAdd semantics: they fill gaps and never override existing entries.
/// </summary>
internal static class AutorediSourceBuilder
{
    private const string MethodPrefix = "AddAutorediServices";

    public static GeneratedResult Generate(ImmutableArray<AutorediTarget> targets, string @namespace, string assemblyName)
    {
        var diagnostics = new List<Diagnostic>();
        var builder = new SourceBuilder();
        builder.AutoGenerated();
        builder.Using("Microsoft.Extensions.DependencyInjection");
        builder.Using("Microsoft.Extensions.DependencyInjection.Extensions");
        builder.Line();

        builder.Namespace(@namespace);

        var validTargets = targets.Where(t => t.IsValid).ToImmutableArray();
        // "All" is reserved for the cross-assembly aggregator emitted by AutorediAllServicesBuilder.
        var claimedNames = new HashSet<string>(StringComparer.Ordinal) { $"{MethodPrefix}All" };

        builder.Class("public static partial", "AutorediServiceCollectionExtensions");
        builder.Block(b =>
        {
            GenerateDefaultServicesMethod(b, validTargets);
            GenerateGroupMethods(b, validTargets, claimedNames, diagnostics);
            GenerateAssemblyWideServicesMethod(b, validTargets, assemblyName, claimedNames, diagnostics);
        });

        return new GeneratedResult(builder.ToString(), diagnostics.ToImmutableArray());
    }

    private static void GenerateDefaultServicesMethod(SourceBuilder builder, ImmutableArray<AutorediTarget> targets)
    {
        GenerateDefaultServicesDocComment(builder);
        builder.Method("public static", "IServiceCollection", MethodPrefix, "this IServiceCollection services");
        builder.Block(b =>
        {
            EmitOrdered(b, targets.Where(t => string.IsNullOrEmpty(t.Group)));
            b.Line("return services;");
        });
        builder.Line();
    }

    private static void GenerateGroupMethods(
        SourceBuilder builder,
        ImmutableArray<AutorediTarget> targets,
        HashSet<string> claimedNames,
        List<Diagnostic> diagnostics)
    {
        var groups = targets
            .Where(t => !string.IsNullOrEmpty(t.Group))
            .Select(t => t.Group!)
            .Distinct()
            .OrderBy(g => g, StringComparer.Ordinal);

        foreach (var raw in groups)
        {
            var fragment = AutorediNaming.ToIdentifierFragment(raw);

            if (!string.Equals(raw, fragment, StringComparison.Ordinal))
            {
                diagnostics.Add(Diagnostic.Create(Diagnostics.InvalidGroupName, Location.None, raw, fragment));
            }

            if (!claimedNames.Add($"{MethodPrefix}{fragment}"))
            {
                diagnostics.Add(Diagnostic.Create(Diagnostics.MethodNameCollision, Location.None, fragment));
                continue;
            }

            builder.Method("public static", "IServiceCollection", $"{MethodPrefix}{fragment}", "this IServiceCollection services");
            builder.Block(b =>
            {
                EmitOrdered(b, targets.Where(t => t.Group == raw));
                b.Line("return services;");
            });
            builder.Line();
        }
    }

    private static void GenerateAssemblyWideServicesMethod(
        SourceBuilder builder,
        ImmutableArray<AutorediTarget> targets,
        string assemblyName,
        HashSet<string> claimedNames,
        List<Diagnostic> diagnostics)
    {
        var assemblySuffix = AutorediNaming.ToIdentifierFragment(assemblyName);
        if (!claimedNames.Add($"{MethodPrefix}{assemblySuffix}"))
        {
            // A group method already owns this name; report so the user can rename one side.
            diagnostics.Add(Diagnostic.Create(Diagnostics.MethodNameCollision, Location.None, assemblySuffix));
            return;
        }

        GenerateFullAssemblyServicesDocComment(builder, assemblyName);
        builder.Method("public static", "IServiceCollection", $"{MethodPrefix}{assemblySuffix}", "this IServiceCollection services");
        builder.Block(b =>
        {
            EmitOrdered(b, targets);
            b.Line("return services;");
        });
        builder.Line();
    }

    private static void EmitOrdered(SourceBuilder builder, IEnumerable<AutorediTarget> targets)
    {
        var ordered = targets
            .OrderByDescending(t => t.Priority)
            .ThenBy(t => t.ImplementationType, StringComparer.Ordinal)
            .ToList();

        // For interface registrations, use TryAdd when a given (serviceType, serviceKey) appears only once
        // within this method's batch – this preserves manual-override (TryAdd checks ServiceType alone)
        // while still allowing multiple implementations via TryAddEnumerable.
        var interfaceCounts = new Dictionary<(string InterfaceType, string? ServiceKey), int>();
        foreach (var target in ordered)
        {
            if (target.InterfaceTypes.IsEmpty) continue;
            foreach (var iface in target.InterfaceTypes.Values)
            {
                var key = (iface, target.ServiceKey);
                interfaceCounts[key] = interfaceCounts.TryGetValue(key, out var c) ? c + 1 : 1;
            }
        }

        foreach (var target in ordered)
        {
            EmitTarget(builder, target, interfaceCounts);
        }
    }

    private static void EmitTarget(SourceBuilder builder, AutorediTarget target, Dictionary<(string InterfaceType, string? ServiceKey), int> interfaceCounts)
    {
        var keyLiteral = target.ServiceKey is null
            ? null
            : SymbolDisplay.FormatLiteral(target.ServiceKey, quote: true);

        if (target.InterfaceTypes.IsEmpty)
        {
            if (keyLiteral is null)
            {
                var directMethod = target.Lifetime switch
                {
                    ServiceLifetime.Singleton => "TryAddSingleton",
                    ServiceLifetime.Scoped => "TryAddScoped",
                    _ => "TryAddTransient"
                };

                builder.Line($"services.{directMethod}<{target.ImplementationType}>();");
            }
            else
            {
                var keyedMethod = target.Lifetime switch
                {
                    ServiceLifetime.Singleton => "TryAddKeyedSingleton",
                    ServiceLifetime.Scoped => "TryAddKeyedScoped",
                    _ => "TryAddKeyedTransient"
                };

                builder.Line($"services.{keyedMethod}<{target.ImplementationType}>({keyLiteral});");
            }

            return;
        }

        var factory = target.Lifetime switch
        {
            ServiceLifetime.Singleton => "Singleton",
            ServiceLifetime.Scoped => "Scoped",
            _ => "Transient"
        };

        foreach (var interfaceType in target.InterfaceTypes.Values)
        {
            var count = interfaceCounts[(interfaceType, target.ServiceKey)];
            var useEnumerable = count > 1;
            if (useEnumerable)
            {
                builder.Line(keyLiteral is null
                    ? $"services.TryAddEnumerable(ServiceDescriptor.{factory}<{interfaceType}, {target.ImplementationType}>());"
                    : $"services.TryAddEnumerable(ServiceDescriptor.Keyed{factory}<{interfaceType}, {target.ImplementationType}>({keyLiteral}));");
            }
            else
            {
                builder.Line(keyLiteral is null
                    ? $"services.TryAdd(ServiceDescriptor.{factory}<{interfaceType}, {target.ImplementationType}>());"
                    : $"services.TryAdd(ServiceDescriptor.Keyed{factory}<{interfaceType}, {target.ImplementationType}>({keyLiteral}));");
            }
        }
    }

    private static void GenerateDefaultServicesDocComment(SourceBuilder builder)
    {
        builder.Line("/// <summary>");
        builder.Line($"/// Registers the default (ungrouped) Autoredi services from this assembly using TryAdd semantics.");
        builder.Line("/// Existing registrations are never overridden.");
        builder.Line("/// </summary>");
        builder.Line("/// <remarks>If no groups are defined, this method registers every service emitted by the assembly.</remarks>");
    }

    private static void GenerateFullAssemblyServicesDocComment(SourceBuilder builder, string assemblyName)
    {
        builder.Line("/// <summary>");
        builder.Line($"/// Registers every Autoredi service emitted by {assemblyName} (all groups included) using TryAdd semantics.");
        builder.Line("/// Existing registrations are never overridden.");
        builder.Line("/// </summary>");
    }
}
